410127248/Controllers/BMIController.cs
using Example.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Example.Controllers
{
    public class BMIController : Controller
    {
        // GET: BMI
        public ActionResult Index()
        {
            return View(new BMIData());
        }
        [HttpPost]
        public ActionResult Index(BMIData data)
        {

            float m_height = data.Height / 100;
            float BMI = data.Weight / (m_height * m_height);
            string level = "";
            if (data.Height < 50 || data.Height> 200)
            {
                ViewBag.HeightError = "身高請輸入50-200的數值";
            }

            if (data.Weight < 30 || data.Weight > 150)
            {
                ViewBag.WeightError = "體中請輸入30-150的數值";
            }
            if (BMI < 18.5)
            {
                level = "體重過輕";
            }
            else if (18.5 <= BMI && BMI < 24)
            {
                level = "正常範圍";
            }
            else if (24 <= BMI && BMI < 27)
            {
                level = "過重";
            }
            else if (27 <= BMI && BMI < 30)
            {
                level = "輕度肥胖";
            }
            else if (30 <= BMI && BMI < 35)
            {
                level = "中度肥胖";
            }
            else if (35 <= BMI)
            {
                level = "重度肥胖";
            }
            data.BMI = BMI;
            data.Level = level;
            return View(data);
        }
    }

}

410127248/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Example.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

410127248/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

410127248/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

410127248/Views/Home/Index.cshtml
@model Example.ViewModel.BMIData
@{
    ViewBag.Title = "Home Page";
}

<form method="post" action="@Url.Action("Index")">
    身高 @Html.TextBoxFor(a=>a.Height)公分 @ViewBag.HeightError <br />
    體重 @Html.TextBoxFor(b=>b.Weight)公斤 @ViewBag.WeightError<br />
    <input type="submit" value="送出" />
</form>
<br />
計算結果： @Model.BMI <br />
等級： @Model.Level

410127248/Views/Shared/Header.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("應用程式名稱", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("首頁", "Index", "Home")</li>
                <li>@Html.ActionLink("關於", "About", "Home")</li>
                <li>@Html.ActionLink("連絡人", "Contact", "Home")</li>
                <li>@Html.ActionLink("BMI計算", "Index", "BMI")</li>
</ul>
        </div>
    </div>
</div>

410127248/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 應用程式</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 應用程式</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>